FROM golang:1.7 AS build
ADD . /src
WORKDIR /src
RUN go get -d -v -t
RUN go test --cover -v ./... --run UnitTest
RUN go build -v -o sams-demo

EXPOSE 8080
ENV DB db
CMD ["sams-demo"]
HEALTHCHECK --interval=10s CMD wget -qO- localhost:8080/demo/hello

RUN mv sams-demo /usr/local/bin/sams-demo
RUN chmod +x /usr/local/bin/sams-demo
